-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.centro_recebimento
(
    id_centro_recebimento serial NOT NULL,
    nome_completo_centro_recebimento character varying(256) COLLATE pg_catalog."default" NOT NULL,
    cpf_cnpj character varying(18) COLLATE pg_catalog."default" NOT NULL,
    telefone_centro_recebimento character varying(16) COLLATE pg_catalog."default" NOT NULL,
    nome_centro_recebimento character varying(256) COLLATE pg_catalog."default" NOT NULL,
    senha_centro_recebimento character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT centro_recebimento_pkey PRIMARY KEY (id_centro_recebimento)
);

CREATE TABLE IF NOT EXISTS public.doadores
(
    id_doador serial NOT NULL,
    nome_doador character varying(256) COLLATE pg_catalog."default" NOT NULL,
    cpf_cnpj character varying(18) COLLATE pg_catalog."default" NOT NULL,
    telefone_doador character varying(16) COLLATE pg_catalog."default",
    email_doador character varying(256) COLLATE pg_catalog."default",
    senha_doador character varying(256) COLLATE pg_catalog."default",
    CONSTRAINT doadores_pkey PRIMARY KEY (id_doador)
);

CREATE TABLE IF NOT EXISTS public.endereco_doadores
(
    id_endereco_doador serial NOT NULL,
    id_doador_endereco integer NOT NULL,
    rua_doador character varying(256) COLLATE pg_catalog."default" NOT NULL,
    bairro_doador character varying(256) COLLATE pg_catalog."default" NOT NULL,
    numero_doador character varying(256) COLLATE pg_catalog."default" NOT NULL,
    complemento_doador character varying(256) COLLATE pg_catalog."default",
    cep_doador character varying(256) COLLATE pg_catalog."default" NOT NULL,
    cidade_doador character varying(256) COLLATE pg_catalog."default",
    uf_doador character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT endereco_doadores_pkey PRIMARY KEY (id_endereco_doador)
);

CREATE TABLE IF NOT EXISTS public.estado
(
    id_estado serial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uf character(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estado_pkey PRIMARY KEY (id_estado)
);

CREATE TABLE IF NOT EXISTS public.municipio
(
    id_cidade serial NOT NULL,
    codigo integer NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uf character(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT municipio_pkey PRIMARY KEY (id_cidade)
);

ALTER TABLE IF EXISTS public.endereco_doadores
    ADD CONSTRAINT endereco_doadores_id_doador_endereco_fkey FOREIGN KEY (id_doador_endereco)
    REFERENCES public.doadores (id_doador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;