/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import util.TipoUsuario;
import util.UsuarioLogado;

/**
 *
 * Tela utilizada capturar o tipo de usuario que acessará o sistema
 */
public class BoasVindas extends javax.swing.JFrame {

    /**
     * Creates new form Escolha
     */
    UsuarioLogado usuarioLogado = new UsuarioLogado();
    TipoUsuario tipoUsuario;

    public BoasVindas() {
        initComponents();
        setIcone();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoCentroRecebimento = new javax.swing.JButton();
        botaoDoador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlCadastrese = new javax.swing.JLabel();
        jcCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olá");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Olá ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Seja Bem-Vindo");

        botaoCentroRecebimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoCentroRecebimento.setText("Centro de Recebimento");
        botaoCentroRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCentroRecebimentoActionPerformed(evt);
            }
        });

        botaoDoador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoDoador.setText("Doador");
        botaoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDoadorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Como deseja acessar?");

        jlCadastrese.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCadastrese.setText("Cadastre-se");
        jlCadastrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadastreseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCadastreseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCadastreseMouseExited(evt);
            }
        });

        jcCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jcCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 181, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(botaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCentroRecebimento)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jlCadastrese, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jcCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCentroRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)))
                .addComponent(jcCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCadastrese)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDoadorActionPerformed
        tipoUsuario = TipoUsuario.DOADOR;
        usuarioLogado.setTipoUsuario(tipoUsuario);
        Login login = new Login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_botaoDoadorActionPerformed

    private void botaoCentroRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCentroRecebimentoActionPerformed
        tipoUsuario = TipoUsuario.CENTRO_RECEBIMENTO;
        usuarioLogado.setTipoUsuario(tipoUsuario);
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCentroRecebimentoActionPerformed

    private void jlCadastreseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastreseMouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        jlCadastrese.setCursor(cursor);
        jlCadastrese.setForeground(Color.BLUE);
    }//GEN-LAST:event_jlCadastreseMouseEntered

    private void jlCadastreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastreseMouseClicked
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlCadastreseMouseClicked

    private void jlCadastreseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastreseMouseExited
        jlCadastrese.setForeground(Color.BLACK);
    }//GEN-LAST:event_jlCadastreseMouseExited

    private void jcCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCadastroActionPerformed
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jcCadastroActionPerformed

    public TipoUsuario getTipoEscolhido() {
        return tipoUsuario;
    }
    public void setIcone(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/resources/img/icone.png")); 
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton botaoCentroRecebimento;
    protected javax.swing.JButton botaoDoador;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JButton jcCadastro;
    protected javax.swing.JLabel jlCadastrese;
    // End of variables declaration//GEN-END:variables
}
