

package view;

import java.awt.Toolkit;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.CentroRecebimento;
import modelo.Cidade;
import modelo.Doador;
import modelo.Endereco;
import modelo.Estado;
import modelo.RuaBairro;
import servico.CentroRecebimentoServico;
import servico.CidadeServico;
import servico.DoadorServico;
import servico.EnderecoServico;
import servico.EstadoServico;
import servico.RuaBairroServico;
import util.VerificaCpf;

/**
 * Tela para o ususario realizar seu cadastro no sistema
 *
 */
public class Cadastro extends javax.swing.JFrame {

    JFormattedTextField jtfCnpj;

    public Cadastro() {
        initComponents();
        setIcone();
        juntaBotoes();
        jtfNomeCentro.setVisible(false);
        jlNomeCentro.setVisible(false);
        popularEstados();
        rbCpf.setSelected(true);
        eventoCep();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesDoadorCentro = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        botoesCpfCnpj = new javax.swing.ButtonGroup();
        painelDadosPessoasi = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jfTelefone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlConfirmarSenha = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JFormattedTextField();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jtfEmail = new javax.swing.JFormattedTextField();
        jtfConfirmarSenha = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JTextField();
        jtfNome = new javax.swing.JFormattedTextField();
        jlNomeCentro = new javax.swing.JLabel();
        jtfNomeCentro = new javax.swing.JTextField();
        rbCpf = new javax.swing.JRadioButton();
        rbCnpj = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        painelCabecalho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbCentroRecebimento = new javax.swing.JRadioButton();
        rbDoador = new javax.swing.JRadioButton();
        painelEndereco = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        cbCidade = new javax.swing.JComboBox<>();
        jlCep = new javax.swing.JLabel();
        jlRua = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlComplemento = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jtfCep = new javax.swing.JFormattedTextField();
        jtfRua = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JFormattedTextField();
        jtfComplemento = new javax.swing.JTextField();
        botaoCadastar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNome.setText("Nome Completo");

        jfTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jfTelefone.setText("Telefone");

        jlEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlEmail.setText("E-mail");

        jlSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlSenha.setText("Senha");

        jlConfirmarSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlConfirmarSenha.setText("Confirmar senha");

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfConfirmarSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlNomeCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeCentro.setText("Nome do Centro de Recebimento");

        jtfNomeCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        rbCpf.setText("CPF");
        rbCpf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCpfItemStateChanged(evt);
            }
        });

        rbCnpj.setText("CNPJ");

        javax.swing.GroupLayout painelDadosPessoasiLayout = new javax.swing.GroupLayout(painelDadosPessoasi);
        painelDadosPessoasi.setLayout(painelDadosPessoasiLayout);
        painelDadosPessoasiLayout.setHorizontalGroup(
            painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                        .addComponent(jlNomeCentro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfTelefone)
                                    .addComponent(jlConfirmarSenha)
                                    .addComponent(jlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlEmail)
                                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                    .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        painelDadosPessoasiLayout.setVerticalGroup(
            painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoasiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCpf)
                        .addGap(1, 1, 1)
                        .addComponent(rbCnpj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfTelefone)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNomeCentro)
                .addGap(18, 18, 18)
                .addComponent(jtfNomeCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConfirmarSenha)
                    .addComponent(jtfConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Novo Usuário");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Como deseja cadastrar-se?");

        rbCentroRecebimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbCentroRecebimento.setText("Centro de Recebimento");
        rbCentroRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentroRecebimentoActionPerformed(evt);
            }
        });

        rbDoador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbDoador.setText("Doador");
        rbDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCentroRecebimento)
                    .addComponent(rbDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCentroRecebimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbDoador)
                .addGap(12, 12, 12))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Estado");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Cidade");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstadoItemStateChanged(evt);
            }
        });

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jlCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCep.setText("CEP");

        jlRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlRua.setText("Rua");

        jlBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlBairro.setText("Bairro");

        jlComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlComplemento.setText("Complemento");

        jlNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNumero.setText("Número");

        try {
            jtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCepKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCepKeyReleased(evt);
            }
        });

        jtfRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        botaoCadastar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoCadastar.setText("Cadastrar");
        botaoCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Endereço");

        javax.swing.GroupLayout painelEnderecoLayout = new javax.swing.GroupLayout(painelEndereco);
        painelEndereco.setLayout(painelEnderecoLayout);
        painelEnderecoLayout.setHorizontalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlRua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlNumero))
                        .addGap(44, 44, 44)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addComponent(jlComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnderecoLayout.createSequentialGroup()
                        .addComponent(botaoCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        painelEnderecoLayout.setVerticalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(64, 64, 64)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRua)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumero)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlComplemento)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(botaoCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(painelDadosPessoasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(428, 428, 428))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelDadosPessoasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(painelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void eventoCep() {
        jtfCep.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                setRuaBairro();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                setRuaBairro();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setRuaBairro();
            }
        });
    }
    private void rbCentroRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentroRecebimentoActionPerformed
        jtfNomeCentro.setVisible(true);
        jlNomeCentro.setVisible(true);


    }//GEN-LAST:event_rbCentroRecebimentoActionPerformed

    private void rbDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoadorActionPerformed

        jtfNomeCentro.setVisible(false);
        jlNomeCentro.setVisible(false);
    }//GEN-LAST:event_rbDoadorActionPerformed

    private void botaoCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastarActionPerformed
        boolean v = validarDados();

        if (rbDoador.isSelected()) {
            if (v == true) {
                cadastrarDoador();

            }
        } else if (rbCentroRecebimento.isSelected()) {
            String nomeCentro = jtfNomeCentro.getText();
            if (v == true && !nomeCentro.isBlank()) {
                cadastrarCentroRecebimento();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma Categoria", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botaoCadastarActionPerformed

    private void cbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstadoItemStateChanged
        cbCidade.removeAllItems();
        popularCidades();
    }//GEN-LAST:event_cbEstadoItemStateChanged

    private void rbCpfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbCpfItemStateChanged
        MaskFormatter mascara = null;
        jtfCpf.setText("");
        jtfCpf.setFormatterFactory(new DefaultFormatterFactory(mascara));

        if (rbCpf.isSelected()) {
            try {
                mascara = new MaskFormatter("###.###.###-##");
            } catch (ParseException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            jtfCpf.setText("");
        } else {
            try {
                mascara = new MaskFormatter("##.###.###/####-##");
            } catch (ParseException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            jtfCpf.setText("");

        }
        jtfCpf.setFormatterFactory(new DefaultFormatterFactory(mascara));

    }//GEN-LAST:event_rbCpfItemStateChanged

    private void jtfCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCepKeyReleased


    }//GEN-LAST:event_jtfCepKeyReleased

    private void jtfCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCepKeyPressed

    }//GEN-LAST:event_jtfCepKeyPressed
    public void habilitaCpf() {
        try {

            jtfCpf.setText("");

            DefaultFormatterFactory mascaraCpf = new DefaultFormatterFactory(new MaskFormatter("###.###.###-##"));
            jtfCpf.setFormatterFactory(mascaraCpf);

            jtfCpf.setText("");
        } catch (java.text.ParseException ex) {
            System.out.println("Deu ruim");
            ex.printStackTrace();
        }
    }

    public void habilitaCnpj() {
        try {

            jtfCpf.setText("");
            MaskFormatter mascaraCnpj = new MaskFormatter("##.###.###/####-##");
            jtfCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCnpj));
            jtfCpf.setText("");
        } catch (java.text.ParseException ex) {
            System.out.println("Deu ruim");
            ex.printStackTrace();
        }

    }
//Metodo que valida se os dados foram digitados corretamente

    public boolean validarDados() {
        if (jtfNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (jtfCpf.getText().length() == 11) {
            VerificaCpf verificarcpf = new VerificaCpf();
            verificarcpf.validaCpf(jtfCpf.getText());
            if (verificarcpf.isResultado() == false) {
                JOptionPane.showMessageDialog(this, "CPF invalido", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else if (jtfCpf.getText().length() != 11 && jtfCpf.getText().length() != 14) {

            return false;
        }
        if (jtfTelefone.getText().length() != 16) {
            JOptionPane.showMessageDialog(this, "Digite corretamente o telefone ", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!jtfEmail.getText().contains("@")) {
            JOptionPane.showMessageDialog(this, "Digite um E-mail valido", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!jtfSenha.getText().equals(jtfConfirmarSenha.getText())) {
            JOptionPane.showMessageDialog(this, "As senhas não corespondem", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jtfCep.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Digite um CEP valido", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String rua, bairro, numero;
        rua = jtfRua.getText();
        bairro = jtfBairro.getText();
        numero = jtfNumero.getText();
        if (rua.isBlank() || bairro.isBlank() || numero.isBlank()) {
            JOptionPane.showMessageDialog(this, "Digite o endereço completo", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    public void juntaBotoes() {
        botoesDoadorCentro.add(rbDoador);
        botoesDoadorCentro.add(rbCentroRecebimento);
        botoesCpfCnpj.add(rbCpf);
        botoesCpfCnpj.add(rbCnpj);

    }
//Metodo para cadastrar um usuario do tipo Doador

    public void cadastrarDoador() {
        Doador doador = new Doador(jtfNome.getText(),
                jtfCpf.getText(),
                jtfTelefone.getText(),
                jtfEmail.getText(),
                jtfSenha.getText());

        DoadorServico doadorServico = new DoadorServico();
        Doador doadorValidacao = doadorServico.salvarNovoDoador(doador);

        if (doadorValidacao != null) {
            System.out.println("Id doador " + doadorValidacao.getIdDoador());
            String estado = String.valueOf(cbEstado.getSelectedItem());
            String cidade = String.valueOf(cbCidade.getSelectedItem());
            int numero = Integer.parseInt(jtfNumero.getText());
            Endereco endereco = new Endereco(estado, cidade, jtfCep.getText(),
                    jtfRua.getText(),
                    jtfBairro.getText(),
                    numero,
                    jtfComplemento.getText());
            EnderecoServico enderecoServico = new EnderecoServico();
            Endereco endValidacao = enderecoServico.salvarEnderecoDoador(endereco, DoadorServico.getIdCadastroDoador());
            if (endValidacao != null) {
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE);
                BoasVindas boasVindas = new BoasVindas();
                boasVindas.setVisible(true);
                this.dispose();

            } else {
                boolean v = doadorServico.apagarDoadorPorId(doadorValidacao.getIdDoador());
                if (v == true) {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar dados no banco", "Erro", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao apagar Doador. Erro ao cadastrar dados no banco", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }
//Metodo para cadastar um usuario do tipo Centro de Recebimento

    public void cadastrarCentroRecebimento() {

        CentroRecebimento centro = new CentroRecebimento(jtfNome.getText(),
                jtfCpf.getText(),
                jtfTelefone.getText(),
                jtfEmail.getText(),
                jtfNomeCentro.getText(),
                jtfSenha.getText());

        CentroRecebimentoServico centroServico = new CentroRecebimentoServico();
        CentroRecebimento centroValidacao = centroServico.salvarCentoRecebimento(centro);
        if (centroValidacao != null) {

            String estado = String.valueOf(cbEstado.getSelectedItem());
            String cidade = String.valueOf(cbCidade.getSelectedItem());
            int numero = Integer.parseInt(jtfNumero.getText());
            Endereco endereco = new Endereco(estado, cidade, jtfCep.getText(),
                    jtfRua.getText(),
                    jtfBairro.getText(),
                    numero,
                    jtfComplemento.getText());
            EnderecoServico enderecoServico = new EnderecoServico();
            Endereco end = enderecoServico.slavarEnderecoCentroRecebimento(endereco, centroServico.getIdCadastroCentroRecebimento());

            if (end != null) {
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE);
                BoasVindas boasVindas = new BoasVindas();
                boasVindas.setVisible(true);
                this.dispose();
            } else {
                boolean v = centroServico.apagarCentroPorId(centroValidacao.getIdCentroRebebimento());
                if (v == true) {
                    System.out.println("id centro = " + centroValidacao.getIdCentroRebebimento());
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar endereço no banco", "Erro", JOptionPane.ERROR_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Apagar Centro. Erro ao cadastrar endereço no banco", "Erro", JOptionPane.ERROR_MESSAGE);

                }
            }
        }

    }
//Metodo que popula o ComBox de "estados" no tela, com informaçoes oriundas do banco de dados
    public void popularEstados() {
        EstadoServico estadoServico = new EstadoServico();
        List<Estado> estados = estadoServico.listaEstados();
        for (Estado i : estados) {
            cbEstado.addItem(i.getSiglaEstado());
        }

    }
//Metodo que popula o ComboBox de "Cidades" baseado no "Estado" escolhido com informações do banco de dados
    public void popularCidades() {
        String uf = String.valueOf(cbEstado.getSelectedItem());
        CidadeServico cidadeServ = new CidadeServico();
        List<Cidade> cidades = cidadeServ.listaCidade(uf);
        for (Cidade i : cidades) {
            cbCidade.addItem(i.getNomeCidade());
        }
    }
//Preenche os campos "Rua" e "Bairro" após ser informado o CEP
    public void setRuaBairro() {
        RuaBairroServico ruaBairroServico = new RuaBairroServico();
        String cep = jtfCep.getText().trim().replaceAll("[.-]", "");
        if (cep.length() == 8) {
            RuaBairro ruaBairro = ruaBairroServico.buscaRuaBairro(cep);
            if (ruaBairro != null) {
                jtfRua.setText(ruaBairro.getRua());
                jtfBairro.setText(ruaBairro.getBairro());
            }
        } else {
            jtfRua.setText("");
            jtfBairro.setText("");
        }
    }
    public void setIcone(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/resources/img/icone.png")); 
    }

    // private JLabel jlNomeCentroRecebimento;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastar;
    private javax.swing.ButtonGroup botoesCpfCnpj;
    private javax.swing.ButtonGroup botoesDoadorCentro;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jfTelefone;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlConfirmarSenha;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeCentro;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCep;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfConfirmarSenha;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfEmail;
    private javax.swing.JFormattedTextField jtfNome;
    private javax.swing.JTextField jtfNomeCentro;
    private javax.swing.JFormattedTextField jtfNumero;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JTextField jtfSenha;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelDadosPessoasi;
    private javax.swing.JPanel painelEndereco;
    private javax.swing.JRadioButton rbCentroRecebimento;
    private javax.swing.JRadioButton rbCnpj;
    private javax.swing.JRadioButton rbCpf;
    private javax.swing.JRadioButton rbDoador;
    // End of variables declaration//GEN-END:variables
}
